import { createLocalJWKSet, decodeProtectedHeader, jwtVerify } from 'jose';

import contract from '../__fixtures__/token_contract.json';

/**
 * Verifies Collections against a token minted by the real MyETM code path.
 *
 * pages/api/me.ts verifies the shared session cookie with `jose`, a completely separate
 * implementation from the Ruby apps' Identity::TokenDecoder. Nothing in either codebase keeps the
 * two in step with how MyETM actually mints tokens, so this pins the contract: the fixture is
 * generated by my-etm (spec/requests/token_contract_spec.rb) and copied to __fixtures__.
 *
 * If this fails after regenerating the fixture, the token change breaks Collections.
 */
describe('token contract with MyETM', () => {
  const jwks = createLocalJWKSet(contract.jwks as Parameters<typeof createLocalJWKSet>[0]);

  // The fixture's tokens carry a real expiry, so verify them as of the moment they were minted.
  const verifyOptions = {
    issuer: contract.issuer,
    algorithms: ['RS256'],
    currentDate: new Date(contract.generated_at * 1000),
  };

  it('accepts the session token MyETM mints', async () => {
    await expect(jwtVerify(contract.session_token, jwks, verifyOptions)).resolves.toBeDefined();
  });

  it('exposes the claims /api/me reads', async () => {
    const { payload } = await jwtVerify(contract.session_token, jwks, verifyOptions);

    expect(payload.sub).toBeTruthy();
    expect(payload.user).toEqual(
      expect.objectContaining({ name: expect.any(String), email: expect.any(String) })
    );
  });

  it('is audienced at Collections', async () => {
    const collections = contract.session_audience.find((url) => url.includes('collections'));
    expect(collections).toBeTruthy();

    await expect(
      jwtVerify(contract.session_token, jwks, { ...verifyOptions, audience: collections })
    ).resolves.toBeDefined();
  });

  it('rejects a token issued by someone else', async () => {
    await expect(
      jwtVerify(contract.session_token, jwks, { ...verifyOptions, issuer: 'https://evil.example' })
    ).rejects.toThrow();
  });

  it('names a key that the published JWKS resolves', () => {
    const { kid } = decodeProtectedHeader(contract.session_token);

    expect(contract.jwks.keys.map((key) => key.kid)).toContain(kid);
  });

  // TODO: TRANSITIONAL — goes when the planned API break invalidates every pre-migration personal access
  // token. Collections does not itself accept PATs, but it shares the JWKS, so the legacy kid must
  // stay resolvable here too.
  it('resolves the legacy kid of a pre-migration token', () => {
    const { kid } = decodeProtectedHeader(contract.legacy_token);

    expect(contract.jwks.keys.map((key) => key.kid)).toContain(kid);
  });
});
